### PR TITLE
Update validators.md

### PR DESCRIPTION
**Pull request by luiis**
Added "Stellar Swiss Group" Node

### CODE REVIEW

**Comment by theaeolianmachine** [comment]
@luiis can you host a stellar.toml file at your domain?

Some basics are [here](https://www.stellar.org/developers/guides/walkthroughs/connect-to-wallets.html#complete-your-stellartoml-file-sep-1) and [the full spec can be found here](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0001.md).

In particular, we'd like to see the `[[VALIDATORS]]` section filled out along with basic information about your organization at a minimum.

Thanks!

**Comment by luiis** [comment]
As requested I added the toml file on the main server (the Swiss one).
https://ch.stellar.lapo.io/.well-known/stellar.toml ;-)
Let me know if there's something else to fix it.

**Comment by theaeolianmachine** [comment]
Thanks @luiis — I think it actually makes sense to update your commit to reference each individual node separately (since they would need to be referenced individually in a quorum configuration), and use the main server as the address listed (since that's where people can find your `stellar.toml`).

**Comment by theaeolianmachine** [comment]
@luiis how is this PR related to #489? Can you update the names of these PRs to reflect the independent changes you're trying to make?

**Comment by theaeolianmachine** [comment]
Hi @luiis, pinging on this and #489.

**Comment by luiis** [comment]
> Hi @luiis, pinging on this and #489.

Yes, we are re-building the architecture to integrate as well the Federation server. Now the correct file is directly on our main domain https://www.lapo.io/.well-known/stellar.toml

**Comment by vcarl** [comment]
I just went through and closed a number of stellar/dashboard PRs for the same reason, but I'm going to close this as well because of stellar/dashboard#107

**Pull request closed without merging**
