### PR TITLE
clarify that inflation is compound (vs simple)

### PR DESCRIPTION
**Pull request by litnerdy**
@jessica-collier @irisli to review/approve

### CODE REVIEW

**Comment by irisli** [comment]
I'm kinda losing my steam in arguing this. But in technical accounting terms, saying "rate" is incorrect because the correct word there should be "yield". They are two *very different things* as the word "rate" is ambiguous. 1% yield compounded weekly is ~0.9951% rate.

Proof that it is yield and not rate:
It is at a rate of .0190721% per 7 days. `1.000190721^(365.24/7)=1.00%`. 
Source:https://github.com/stellar/stellar-core/blob/4d8ecabe3556f7f33d39fb550e5deca4ee6abb94/src/transactions/InflationOpFrame.cpp#L15

Current:
```
New lumens are added to the network at the rate of 1% each year (compounding—the 1% includes lumens from previous inflation rounds).
```

My suggestion (minor but more accurate):
```
New lumens are added to the network at a yield of 1% each year (compounded every 7 days—the 1% includes lumens from previous inflation rounds).
```

**Comment by irisli** [comment]
Of course, I am not an accountant. But I am annoying and believe myself to be correct (which I may very well be incorrect; and often times I am incorrect).

**Comment by jedmccaleb** [comment]
"added to the network at a yield.." doesn't make sense. You would have to say "with a yield" which doesn't make sense here. 

I don't think the edit clarifies the situation though. So probably best to leave it as is.

If you really want to change it I would just say: "Lumens are added to the network at the rate of 1% new lumens each year."

**Comment by irisli** [comment]
Yeah, I don't think we need to say "compounded" since it's also ambiguous. I think the most exact way without ambiguities is to just say:

> New lumens are added to the network at a 1% annual percentage yield (APY).

If someone asks if it's compounded, we can answer them, but it is implicitly implied and it doesn't change the fact that there is 1 percent yield.

I lean on the side of just keeping it simpler (since my suggestion (and the current suggestion) seems confusing).

**Comment by irisli** [comment]
Okay, I have given my 2 stroops. I'm fine with anything other people agree on.

**Comment by litnerdy** [comment]
IMO it's more important to be clear that technically correct/accurate. I think far more people will understand the sentence as-is, but ultimately I think it's a @jessica-collier question (or maybe @Mr0grog )

**Comment by Mr0grog** [comment]
Is this change solving an actual person’s problem or just one we perceive? If the former, who’s asking? Who’s the audience you’re trying to explain to here? The words should fit *them.*

That said, *my understanding* is that APY is a very specific term *in the US,* APR is a somewhat consistent term in the US, and “rate” and “yield” are both pretty inconsistently applied. In any case, though, I am not a particularly financially-minded person, and had to do a fair amount of hard thinking just to put together that sentence. Trying to differentiate the above terms and get them right is *hard.* If I were re-writing that first paragraph for me, I might say something like:

> The Stellar network has built-in inflation—the total number of lumens grows by 0.019% each week and compounds to create a growth of 1% over the course of a year. Those new lumens are distributed based on votes from all the accounts on the network.

**Comment by Mr0grog** [comment]
Or if looking for more detail:

> The Stellar network has built-in inflation—the total number of lumens grows by 0.019% each week and compounds to create a growth of 1% over the course of a year. The growth each week includes the new lumens that were added the week before, so the increase is a little bit bigger each week. Those new lumens are distributed based on votes from all the accounts on the network.

**Pull request closed without merging**
