### PR TITLE
docs/guides Brazilian Portuguese Translation

### PR DESCRIPTION
**Pull request by pedropran**
Issue #388

### CODE REVIEW

**Comment by jedmccaleb** [comment]
Hey thanks for this!  It looks like you just replaced the english files with the Portuguese ones. They should be in some separate folder so the english version doesn't get stepped on.

**Comment by theaeolianmachine** [comment]
Hey @pedropran - any way you could move these to a separate folder?

**Comment by pedropran** [comment]
@theaeolianmachine, @jedmccaleb Thanks. I just made a separate directory.

**Comment by theaeolianmachine** [comment]
Thanks so much @pedropran - could you fix your merge conflicts here? It'd be preferred that you rebase your changes on top of the latest changes in the master branch, and force push (overwriting the branch) your changes up.

**Comment by edunuzzi** [comment]
@theaeolianmachine Thanks a lot for the suggestions. Since all previous commits were modifying the original files, we created new ones adding the new translated files to a 'translations' folder. We rebased all the changes on top of the master branch and solved all the conflicts.

**Comment by theaeolianmachine** [comment]
This is awesome - thank you so much @edunuzzi and @pedropran, and again, apologies on the long wait.

**Comment by theaeolianmachine** [comment]
@bartekn - As a heads up, I made sure that the developers site still built and nothing was clobbered.

**Pull request merged**
