### PR TITLE
correct passive offer docs

### PR DESCRIPTION
**Pull request by MonsieurNicolas**
https://stellar.stackexchange.com/questions/4381/can-not-delete-create-passive-sell-offer

### CODE REVIEW

**Comment by ire-and-curses** [comment]
I think this also needs fixing here: https://github.com/stellar/new-docs/blob/master/content/docs/start/list-of-operations.mdx

**Comment by bartekn** [comment]
There's also a reference to deletion in the beginning of the section:
> Creates, updates, or **deletes** an offer to sell one asset for another, otherwise known as a "ask"
order or "offer" on a traditional orderbook, _without taking a reverse offer of equal price_.	order or "offer" on a traditional orderbook, _without taking a reverse offer of equal price_.

**Comment by MonsieurNicolas** [comment]
updated.

inflation add in the index is auto generated, so I marked it as deprecated instead or removing it

**Review by bartekn — APPROVED** [review]

**Comment by rice2000** [comment]
Also here: https://github.com/stellar/new-docs/pull/347

**Pull request merged**
