### PR TITLE
add new federation type

### PR DESCRIPTION
**Pull request by jedmccaleb**

### CODE REVIEW

**Comment by bartekn** [comment]
To be honest, I don't like this solution for two reasons:
* sending JSON in query params is prone to errors, hard to read and should really be sent in POST,
* list of fields in JSON is not defined anywhere so it's hard to tell what needs to be sent.

What if we allowed `type` field to be anything, in this case `bank_account`. For each type there will be a list of required fields in FI `stellar.toml` file. These fields will be sent in query params like:
```
/federation?type=bank_account&bank=BNORPHMM&acct=187663627
```

**Comment by jedmccaleb** [comment]
Yeah I get that JSON as a parameter is gross.
I suppose we could just have it be:
https://YOUR_FEDERATION_SERVER/federation?type=forward&custom=blah&acct=grover

Then just a comment in the stellar.toml saying what you need/expect from the other parameters in the request.

**Comment by bartekn** [comment]
> I don't see an advantage of having be something other than a comment.

You could build a form and display it to user if it was key -> caption mapping.

**Comment by nullstyle** [comment]
+1 to jed's latest proposal.

IMO, we should recommend to people the convention of using `forward_type` to further discriminate the lookup operation being performed:

`/federation?type=forward&forward_type=bank_account&acct=1234` as an example.

It shouldn't be required, but this model should be recommended.  IMO it will allow for easier inclusion of any popular schemes into the primary federation standard.

**Comment by jedmccaleb** [comment]
yeah that makes sense

**Pull request merged**
