### PR TITLE
MEMO_TEXT ASCII

### PR DESCRIPTION
**Pull request by bartekn**

### CODE REVIEW

**Comment by jedmccaleb** [comment]
they can put utf-8 in there

**Comment by bartekn** [comment]
The problem is that they can also put ASCII there but someone else may expect UTF8 what can lead to a bugs like the recent one in horizon. I think we should explicitly say that it's ASCII.

If someone wants to put UTF8 there then it's OK, she can interpret it as UTF8 in her code that is **also** handling _non_ UTF8 string properly.

**Comment by bartekn** [comment]
@tipbot 10 @jedmccaleb

**Comment by jedmccaleb** [comment]
@tipbot 10 @bartekn

**Comment by jedmccaleb** [comment]
But it works fine if people put utf8 there now. I don't want it to seem that we don't support that.

**Comment by jedmccaleb** [comment]
@tipbot @bartekn

**Comment by nullstyle** [comment]
At the very least we need to better specify "string".  I'm fine with saying "A string encoded using either ASCII or UTF-8".  UTF-8 is backwards compatible with ASCII, so it shouldn't confuse someone or complicate an integration.

**Comment by nullstyle** [comment]
Ping @bartekn.  Let's add a note about UTF-8 and merge this, eh?

**Comment by bartekn** [comment]
Done.

**Pull request merged**
