### PR TITLE
Update validators.md

### PR DESCRIPTION
**Pull request by smdwireless**
Updated localstellarassets.com to its new name and domain tradedirect.io

### CODE REVIEW

**Comment by smdwireless** [comment]
@theaeolianmachine apologies, issue fixed, please try again.

**Comment by theaeolianmachine** [comment]
Thanks for fixing that — I don't see that you have a Stellar TOML file hosted at https://www.tradedirect.io/.well-known/stellar.toml. Can you please host your TOML file there?

**Comment by smdwireless** [comment]
doh... sorry forgot to change the directory inside the server from the old localstellarassets.com
Fixed now, thanks.

**Comment by theaeolianmachine** [comment]
Yup, see it now — thanks! Will merge this in.

**Comment by theaeolianmachine** [comment]
(and yes, thanks for pointing out my additional www, my bad).

**Pull request merged**
