### PR TITLE
Update validators.md

### PR DESCRIPTION
**Pull request by andreaborio**
added A World validator

### CODE REVIEW

**Comment by theaeolianmachine** [comment]
@andreaborio can you point me to where your stellar.toml file is hosted? Would like to verify that against this listing. Couldn't find it at `stellar.aworld.org` or `[www.]aworld.org`.

**Comment by andreaborio** [comment]
@theaeolianmachine I'll update you here when the TOML is uploaded at the moment my colleague who manages the hosting of aworld.org is abroad

**Comment by andreaborio** [comment]
@theaeolianmachine https://aworld.org/.well-known/stellar.toml here you can find our TOML, for the moment we don't have any public account or token on the public network

**Comment by theaeolianmachine** [comment]
Thanks!

**Pull request merged**
