### PR TITLE
New Validator added

### PR DESCRIPTION
**Pull request by Dilidonka**
Add one more validator from Goodx Network de2.stellar.goodx.network

### CODE REVIEW

**Comment by theaeolianmachine** [comment]
Hey @Dilidonka, is this server actually based in the US? I looked this up on [Stellarbeat](https://stellarbeat.io/nodes) and noted that the IP address (which matches us.stellar.goodx.network) is based out of Germany (like the other node)? Would just like to confirm this before merging this in, as we don't want to state it's based out of the US when it isn't.

**Comment by Dilidonka** [comment]
> Hey @Dilidonka, is this server actually based in the US? I looked this up on [Stellarbeat](https://stellarbeat.io/nodes) and noted that the IP address (which matches us.stellar.goodx.network) is based out of Germany (like the other node)? Would just like to confirm this before merging this in, as we don't want to state it's based out of the US when it isn't.

Sorry for confusing you, it's in germany. To avoid any misunderstanding in future renamed it to 
de2.stellar.goodx.network

**Comment by theaeolianmachine** [comment]
Can you rename it in the pull request as well?

**Comment by theaeolianmachine** [comment]
Thanks!

**Comment by Dilidonka** [comment]
Appreciate your support!

**Pull request merged**
