### PR TITLE
Update Java getBalance example for current API

### PR DESCRIPTION
**Pull request by Synesso**
AccountRequestBuilder.account no longer takes accountId

### CODE REVIEW

**Comment by bartekn** [comment]
It takes `KeyPair` object, so example is correct: https://github.com/stellar/java-stellar-sdk/blob/master/src/main/java/org/stellar/sdk/requests/AccountsRequestBuilder.java#L46

Will reopen if I'm missing something.

**Comment by Synesso** [comment]
Correct, but the docs currently use `String`. I changed it to `KeyPair`.

**Comment by bartekn** [comment]
🤦‍♂️

**Comment by bartekn** [comment]
Thanks!

**Pull request merged**
