### PR TITLE
additional grammar suggestions

### PR DESCRIPTION
**Pull request by kylemccollom**

### CODE REVIEW

**Comment by tomerweller** [comment]
Thanks @kylemccollom. Please sign the contributor agreement: https://docs.google.com/forms/d/e/1FAIpQLSdoiChpRJ5vZnqRKK7WsHiUcaTO90hs7nuHIyOb5GDVsgvT8w/viewform

**Comment by nikhilsaraf** [comment]
@kylemccollom please resolve conflicts, thanks.

**Comment by kylemccollom** [comment]
done

**Comment by nikhilsaraf** [comment]
thanks!

**Pull request merged**
