### PR TITLE
Add Wirex validators

### PR DESCRIPTION
**Pull request by staspikin**

### CODE REVIEW

**Comment by theaeolianmachine** [comment]
Thanks @staspikin! Have you all added a [SEP-6 server](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0006.md) yet (this would go under `TRANSFER_SERVER`, see [SEP-0001 docs](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0001.md))?

Otherwise, looks good.

**Comment by theaeolianmachine** [comment]
Actually ignore that, since you don't have any assets listed yet, but I would recommend it once you do (along with any accounts (`ACCOUNTS`) this domain runs that you want to be public; in particular issuing accounts). 

I'd suggest putting your `[QUORUM_SET]` in your TOML file — once you get a chance to do this, I'll merge it in.

**Comment by staspikin** [comment]
@theaeolianmachine okay, I'll ask to update it tomorrow.

**Comment by staspikin** [comment]
@theaeolianmachine stellar.toml has been updated.

**Comment by theaeolianmachine** [comment]
Excellent, thank you!

**Pull request merged**
