### PR TITLE
Added White Wallet Validator

### PR DESCRIPTION
**Pull request by thewhitecompany**
White Wallet validator is now live

### CODE REVIEW

**Comment by thewhitecompany** [comment]
Here it is: https://thewwallet.com/.well-known/stellar.toml
If there any questions about the setup, let us know. The documentation for Validator setup was used as reference but it there's other best practices that need to be implemented, we can certainly do so

**Comment by tomquisel** [comment]
Nice! That looks close. I think `OUR_VALIDATORS` should list the validator nodes you're running. You're not running the SatoshiPay validators, right? I'd also add `TRANSFER_SERVER` to make your SEP-6 setup discoverable. Check out the [SEP-1 docs](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0001.md) for full details if you haven't already.

**Comment by theaeolianmachine** [comment]
Hi @thewhitecompany, have you had a chance to update your TOML file? Would be happy to merge this in once those are covered.

**Comment by thewhitecompany** [comment]
Hi @tomquisel @theaeolianmachine we appreciate your comments. We have updated both the "Our Validators' to reflect our current node address/account as well as the transfer server to point to the location of our API (which is compatible with the SEP-0006 deposit/withdraw function). Let me know if anything else is recommended.

**Comment by theaeolianmachine** [comment]
@thewhitecompany I ran into a few more items to take a look at:

- I'm getting 404's on the transfer server on multiple endpoints (even on /info) at https://thewwallet.com/ExtApi.
- `GDSVWEA7XV6M5XNLODVTPCGMAJTNBLZBXOFNQD3BNPNYALEYBNT6C` is the issuing account for many of your assets — if you control it, can you move it to `ACCOUNTS` as well? It points to your domain as its home domain.
- `GBH42X7GG5TQLBMKY2KNYQ6KY7XOUALQCUUZQH5EOLVNULDJMLCNUNJP` isn't a valid stellar account, but it's listed under `ACCOUNTS` — perhaps you meant to list the above public key, since this is your listed validator public key?.

**Comment by theaeolianmachine** [comment]
Hi @thewhitecompany, checking in again.

**Comment by theaeolianmachine** [comment]
I'm going to close this out for now — feel free to ping on this thread or open a new PR once the above points have been addressed. Thanks!

**Pull request closed without merging**
