### PR TITLE
remove "XLM" from docs

### PR DESCRIPTION
**Pull request by litnerdy**

### CODE REVIEW

**Comment by jedmccaleb** [comment]
@jessica-collier  XLM is all over the docs. Do you want it or change everything to lumens?

**Comment by litnerdy** [comment]
@jedmccaleb @jessica-collier The reason I'd like to change it is that @nullstyle says it's no longer technically accurate - asset codes work differently in the upgraded network, and there isn't any code for the native currency.

**Comment by jessica-collier** [comment]
XLM is pervasive throughout the docs, but keeping it also depends on whether we'll use the code in any other public-facing way. @jedmccaleb are we still using XLM as our ISO 4217 code?

**Comment by jedmccaleb** [comment]
Yeah I sort of think it makes sense to leave it. I think people will use it in clients. exchanges will certainly use it.

**Comment by nullstyle** [comment]
Do we prevent people from issuing currencies on the XLM code?  If not, this is going to be confusing.

**Comment by jessica-collier** [comment]
After face-to-face convo, sounds like we're agreed that XLM can continue to be our ISO code and that any user-issued currencies that try to adopt "lumens" or "XLM" will be taken care of in a more direct way.

**Pull request closed without merging**
